name: app_string_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  app_strings:
    path: ../
  easy_localization: ^3.0.7+1
  flutter:
    sdk: flutter

dependency_overrides:
  path: ^1.9.0
  meta: ^1.15.0

  

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
